# Generated by Django 2.2.4 on 2020-02-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(default='WRITE DESCRIPTION', max_length=265),
        ),
    ]
